### ISSUE TITLE
version 13 can not install on fresh Ubuntu 18.04LTS

### ISSUE THREAD

**Issue by BanilSharma** [JayVora-SerpentCS/OdooEduERP#158]
the below error 
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo13/odoo13-server/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo13/odoo13-server/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo13/odoo13-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo13/odoo13-server/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/odoo13/odoo13-server/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo13/odoo13-server/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo13/odoo13-server/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo13/odoo13-server/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/odoo13/odoo13-server/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/odoo13/odoo13-server/addons/web/controllers/main.py", line 1324, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo13/odoo13-server/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo13/odoo13-server/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo13/odoo13-server/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/odoo13/odoo13-server/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo13/odoo13-server/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo13/odoo13-server/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo13/odoo13-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo13/odoo13-server/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo13/odoo13-server/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo13/odoo13-server/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/odoo13/odoo13-server/odoo/modules/module.py", line 382, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/odoo13/odoo13-server/addons/school/__init__.py", line 7, in <module>
    from . import models
  File "/odoo13/odoo13-server/addons/school/models/__init__.py", line 7, in <module>
    from . import school
  File "/odoo13/odoo13-server/addons/school/models/school.py", line 29, in <module>
    class AcademicYear(models.Model):
  File "/odoo13/odoo13-server/addons/school/models/school.py", line 58, in AcademicYear
    @api.multi
AttributeError: module 'odoo.api' has no attribute 'multi'

**Comment by JayVora-SerpentCS** [comment]
@BanilSharma Thank you for reporting, the v13 is in progress.
It has been fixed now, please fetch the latest code.
Thanks,

**Comment by BanilSharma** [comment]
this issue still persists on fresh install 
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo13/odoo13-server/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo13/odoo13-server/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo13/odoo13-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo13/odoo13-server/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/odoo13/odoo13-server/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo13/odoo13-server/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo13/odoo13-server/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo13/odoo13-server/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/odoo13/odoo13-server/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/odoo13/odoo13-server/addons/web/controllers/main.py", line 1324, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo13/odoo13-server/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo13/odoo13-server/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo13/odoo13-server/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "/odoo13/odoo13-server/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo13/odoo13-server/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo13/odoo13-server/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo13/odoo13-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo13/odoo13-server/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo13/odoo13-server/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo13/odoo13-server/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/odoo13/odoo13-server/odoo/modules/module.py", line 382, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/odoo13/odoo13-server/addons/school/__init__.py", line 7, in <module>
    from . import models
  File "/odoo13/odoo13-server/addons/school/models/__init__.py", line 8, in <module>
    from . import student
  File "/odoo13/odoo13-server/addons/school/models/student.py", line 22, in <module>
    class StudentStudent(models.Model):
  File "/odoo13/odoo13-server/addons/school/models/student.py", line 109, in StudentStudent
    @api.multi
AttributeError: module 'odoo.api' has no attribute 'multi'
